services:
  - type: web
    name: capture-moments
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    runtime: python
    pythonVersion: 3.10
    autoDeploy: true
